name = "SnelliusDebug"
uuid = "feda92c9-92cf-4270-8a72-c71b802743be"
authors = ["Oriol Colomes <oriol.colomes@gmail.com>"]
version = "0.1.0"

[deps]
GridapPETSc = "bcdc36c2-0c3e-11ea-095a-c9dadae499f1"
MPIPreferences = "3da0fdf6-3ccc-4f1b-acd9-58baa6c99267"
PackageCompiler = "9b87118b-4619-50d2-8e1e-99f35a4d4d9d"
